# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from pynab.openapi.configuration import Configuration


class ScheduledTransactionResponseData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'scheduled_transaction': 'ScheduledTransactionDetail'
    }

    attribute_map = {
        'scheduled_transaction': 'scheduled_transaction'
    }

    def __init__(self, scheduled_transaction=None, local_vars_configuration=None):  # noqa: E501
        """ScheduledTransactionResponseData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._scheduled_transaction = None
        self.discriminator = None

        self.scheduled_transaction = scheduled_transaction

    @property
    def scheduled_transaction(self):
        """Gets the scheduled_transaction of this ScheduledTransactionResponseData.  # noqa: E501


        :return: The scheduled_transaction of this ScheduledTransactionResponseData.  # noqa: E501
        :rtype: ScheduledTransactionDetail
        """
        return self._scheduled_transaction

    @scheduled_transaction.setter
    def scheduled_transaction(self, scheduled_transaction):
        """Sets the scheduled_transaction of this ScheduledTransactionResponseData.


        :param scheduled_transaction: The scheduled_transaction of this ScheduledTransactionResponseData.  # noqa: E501
        :type scheduled_transaction: ScheduledTransactionDetail
        """
        if self.local_vars_configuration.client_side_validation and scheduled_transaction is None:  # noqa: E501
            raise ValueError("Invalid value for `scheduled_transaction`, must not be `None`")  # noqa: E501

        self._scheduled_transaction = scheduled_transaction

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduledTransactionResponseData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ScheduledTransactionResponseData):
            return True

        return self.to_dict() != other.to_dict()
